version: "2.2"  # https://docs.docker.com/compose/compose-file/
services:
  husarnet-ssh:
    build: ./
    volumes:
      - husarnet-ssh-v:/var/lib/husarnet
    env_file: 
      - ./.env  # create .env file in the same folder as Dockerfile and specify HOSTNAME and JOINCODE there
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add: 
      - NET_ADMIN
    stdin_open: true # docker run -i
    tty: true        # docker run -t

volumes:
  husarnet-ssh-v: