name: Docker Build/Publish Image 

on:
  push:
    branches:
      - 'main'
  
jobs:
  build:
    runs-on: ubuntu-latest

    env:      
      DOCKER_REGISTRY: registry.hub.docker.com
      DOCKER_IMAGE: donowak/docker-example
      DOCKER_TARGET_PLATFORM: linux/arm/v7
      
    steps:
    - name: Checkout the code
      uses: actions/checkout@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
    # - name: Set up Docker Buildx
    #   uses: crazy-max/ghaction-docker-buildx@v1
    #   with:
    #     version: latest
          
    - name: Prepare
      if: success()
      id: prepare
      run: |
        echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}
        echo ::set-output name=docker_image::${DOCKER_REGISTRY}/${DOCKER_IMAGE}
        echo ::set-output name=version::${GITHUB_RUN_NUMBER}
          
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Run Buildx (push image)
      if: success()
      run: |
        docker buildx build \
        --platform ${{ steps.prepare.outputs.docker_platform }} \
        --tag ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }} \
        --file ./Dockerfile \
        --output type=image,push=true .